#include "GaudiKernel/DeclareFactoryEntries.h"
#include "rhopi_pipigg/rhopi_pipigg.h"

DECLARE_ALGORITHM_FACTORY(D0omega_K4pi)
DECLARE_FACTORY_ENTRIES(D0omega_K4pi)
{
  DECLARE_ALGORITHM(D0omega_K4pi);
}

DECLARE_ALGORITHM_FACTORY(D0phi_KpipiKK)
DECLARE_FACTORY_ENTRIES(D0phi_KpipiKK)
{
  DECLARE_ALGORITHM(D0phi_KpipiKK);
}

DECLARE_ALGORITHM_FACTORY(D0phi_3K3pi)
DECLARE_FACTORY_ENTRIES(D0phi_3K3pi)
{
  DECLARE_ALGORITHM(D0phi_3K3pi);
}

DECLARE_ALGORITHM_FACTORY(D0phi_KpiKK)
DECLARE_FACTORY_ENTRIES(D0phi_KpiKK)
{
  DECLARE_ALGORITHM(D0phi_KpiKK);
}

DECLARE_ALGORITHM_FACTORY(rhopi_pipigg)
DECLARE_FACTORY_ENTRIES(rhopi_pipigg)
{
  DECLARE_ALGORITHM(rhopi_pipigg);
}