#include "GaudiKernel/LoadFactoryEntries.h"

LOAD_FACTORY_ENTRIES(TrackSelector)
LOAD_FACTORY_ENTRIES(D0omega_K4pi)
LOAD_FACTORY_ENTRIES(D0phi_KpipiKK)
LOAD_FACTORY_ENTRIES(D0phi_3K3pi)
LOAD_FACTORY_ENTRIES(D0phi_KpiKK)
LOAD_FACTORY_ENTRIES(rhopi_pipigg)
